### ISSUE TITLE
Add HDF5 Viewer to the stack 

### ISSUE THREAD

**Issue by LukasGold** [OpenSemanticLab/docker-compose-osl-wiki#37]

**Comment by simontaurus** [comment]
see https://github.com/OpenSemanticLab/docker-compose-osl-wiki/commit/c6b69cf62c2aa62270155fd3d4d75c22e912d6e6, https://github.com/OpenSemanticLab/docker-compose-osl-wiki/commit/4d307b02bc0ca9301cbf147bdfd880c5f267c632
